name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Clean Flutter
      run: flutter clean
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Verify Flutter files
      run: |
        ls -la ios/Flutter/
        cat ios/Flutter/Generated.xcconfig || echo "Generated.xcconfig not found"
        
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --repo-update
        
    - name: Build iOS app (no signing)
      run: |
        flutter build ios --release --no-codesign
      env:
        FLUTTER_BUILD_MODE: release
        
    - name: List build artifacts
      run: |
        find build -name "*.app" -type d
        ls -la build/ios/iphoneos/ || echo "No build directory found"
        
    - name: Create IPA manually
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../jumpz.ipa Payload/
        ls -la ../../jumpz.ipa
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: jumpz-app
        path: build/jumpz.ipa
        retention-days: 30
      if: always()
