name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: |
        flutter pub get
        flutter pub deps
        
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install
        
    - name: Build iOS app (no signing)
      run: |
        flutter build ios --release --no-codesign --verbose
      env:
        FLUTTER_BUILD_MODE: release
        
    - name: Create IPA manually
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../jumpz.ipa Payload/
        ls -la ../../jumpz.ipa
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: jumpz-app
        path: build/jumpz.ipa
        retention-days: 30
      if: always()
