name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: |
        flutter pub get
        flutter pub deps
        
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install
        
    - name: Clean and prepare build
      run: |
        flutter clean
        flutter pub get
        mkdir -p build/ios
        
    - name: Build iOS app (Flutter)
      run: |
        flutter build ios --release --no-codesign --verbose
      env:
        FLUTTER_BUILD_MODE: release
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        
    - name: Check build logs
      run: |
        echo "=== Build Directory Contents ==="
        find build -type f -name "*.log" -exec echo "=== {} ===" \; -exec cat {} \;
        echo "=== iOS Build Directory ==="
        ls -la build/ios/ || echo "No iOS build directory"
        echo "=== Xcode Build Logs ==="
        find build -name "*.log" -exec echo "=== {} ===" \; -exec head -50 {} \;
      if: failure()
        
    - name: Create IPA manually
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../jumpz.ipa Payload/
        ls -la ../../jumpz.ipa
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: jumpz-app
        path: build/jumpz.ipa
        retention-days: 30
      if: always()
