name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Clean Flutter
      run: flutter clean
      
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install --repo-update
        
    - name: Build iOS app
      run: |
        flutter build ipa --release --verbose
      env:
        FLUTTER_BUILD_MODE: release
        
    - name: List build artifacts
      run: |
        find build -name "*.ipa" -type f
        ls -la build/ios/ipa/ || echo "No IPA directory found"
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: jumpz-app
        path: build/ios/ipa/*.ipa
        retention-days: 30
      if: always()
