name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Install dependencies
      run: |
        flutter pub get
        flutter pub deps
        
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install
        
    - name: Build iOS app (Flutter)
      run: |
        flutter build ios --release --no-codesign --verbose
      env:
        FLUTTER_BUILD_MODE: release
        
    - name: Check build output
      run: |
        echo "=== Build Directory Contents ==="
        find build -type f -name "*.app" -exec echo "Found app: {}" \;
        find build -type d -name "iphoneos" -exec echo "Found iphoneos: {}" \;
        ls -la build/ || echo "No build directory"
        ls -la build/ios/ || echo "No iOS build directory"
        
    - name: Create IPA manually
      run: |
        if [ -d "build/ios/iphoneos" ]; then
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../jumpz.ipa Payload/
          ls -la ../../jumpz.ipa
        else
          echo "No iphoneos directory found, checking alternatives..."
          find build -name "*.app" -exec echo "Found app: {}" \;
        fi
        
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: jumpz-app
        path: build/jumpz.ipa
        retention-days: 30
      if: always()
