name: Simple iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Install CocoaPods
      run: |
        cd ios
        sudo gem install cocoapods
        pod install
        
    - name: Build iOS app
      run: flutter build ios --release --no-codesign
      
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../jumpz.ipa Payload/
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: jumpz-app
        path: build/jumpz.ipa
        retention-days: 30
